blank_issues_enabled: false
contact_links:
  - name: Suggestions for other topics
    url: https://smutje.app/hub/suggestions
    about: If you have suggestions on topics not related to the website or services, please click here.
